### ISSUE TITLE
Doesn't work with non-flattened contracts

### ISSUE THREAD

**Issue by paulrberg** [tintinweb/smart-contract-inspector#10]
I tried to load the Sablier v1.1 contract (CD18eAa163733Da39c232722cBC4E8940b1D8888) but it couldn't be loaded:

<img width="1792" alt="Capture d’écran 2021-07-31 à 12 22 20" src="https://user-images.githubusercontent.com/8782666/127735409-3750e1a2-5569-4012-96c8-73fdd9673804.png">

The contract was compiled with Solidity v0.5.17

**Comment by tintinweb** [comment]
Hey @paulrberg,

looks like an etherscan.io issue. The contract code should show the flattened solidity source code while in this case it shows a json response. I assume that the etherscan API returned this garbage 🙄. We haven't implemented some heuristic to detect the various different responses the API provides. Please try to manually copy the flattened source code into the textbox.

cheers,
tin

**Comment by paulrberg** [comment]
Hey @tintinweb, this contract has been verified with the "multi-part" compiler file. As you can see on the [Contract code](https://etherscan.io/address/0xCD18eAa163733Da39c232722cBC4E8940b1D8888#code) tab, there are 9 files in total which make up the verification of the source code of 0xCD18eAa163733Da39c232722cBC4E8940b1D8888.

This is likely going to continue being a problem for other users in the future. Hopefully you will find the time to support non-flattened source code verifications :)

**Comment by mds1** [comment]
Hey! Just wanted +1 on support for multi-part contract support. There's some mainnet contracts I'd love to drop into this tool, but flattening their 27 parts would be a hassle 🙂
